name: qccodar
channels:
  - conda-forge
  - defaults
dependencies:
  - docopt
  - geopy
  - ipython
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - oceans
  - pandas
  - seawater
  - xarray
  - watchdog
  - pip
  - pip:
    - hfradarpy
